### ISSUE TITLE
Update NodeJS logo

### ISSUE THREAD

**Issue by vkatsuba** [oda-components/oda-components.github.io#11]
The logo of NodeJS is looks messed in Web page it related to point that the template is try display in a round frame the images.

**Comment by vances** [comment]
This was solved in commit commit [dc1b3](https://github.com/oda-components/oda-components.github.io/commit/dc1b35af5174d78fe49acadaafe550b817f6dd2d) by removing the `rounded-circle` class.

**Comment by vkatsuba** [comment]
Reopen by reason that the logo is broken in page https://www.oda-components.org/html/nodejs-sdk.html
